# Generated by Django 6.0.7 on 2026-08-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('type', models.CharField(choices=[('validator', 'Validator'), ('builder', 'Builder'), ('ai-generated', 'AI Generated')], default='validator', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('needs-fixes', 'Needs Fixes'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('framework', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('html_path', models.CharField(blank=True, default='', max_length=500)),
                ('css_path', models.CharField(blank=True, default='', max_length=500)),
                ('js_path', models.CharField(blank=True, default='', max_length=500)),
                ('ts_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='landingpages.landingpageproject')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_reports', to='landingpages.landingpageproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_reports', to='landingpages.landingpageversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('category', models.CharField(choices=[('syntax', 'Syntax'), ('accessibility', 'Accessibility'), ('seo', 'SEO'), ('security', 'Security'), ('performance', 'Performance'), ('responsive', 'Responsive')], max_length=20)),
                ('rule_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('file', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('cdn', 'CDN')], max_length=20)),
                ('line', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, default='')),
                ('auto_fixable', models.BooleanField(default=False)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='landingpages.validationreport')),
            ],
            options={
                'ordering': ['line', 'column'],
            },
        ),
        migrations.AddConstraint(
            model_name='landingpageproject',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_landingpage_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='landingpageversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_landingpage_version_number_per_project'),
        ),
    ]
