# Generated by Django 6.0.7 on 2026-08-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='code_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='confidence',
            field=models.CharField(choices=[('definite', 'Definite'), ('likely', 'Likely'), ('possible', 'Possible')], default='definite', max_length=10),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='deterministic_fix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='end_column',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='end_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='engine_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='fix_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('insert-closing-tag', 'Insert closing tag'), ('add-attribute', 'Add attribute'), ('remove-duplicate', 'Remove duplicate')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='related_attribute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='related_element',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='requires_manual_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='source_engine',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='standards_reference',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='engine_status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='profile',
            field=models.CharField(choices=[('standard', 'Standard'), ('strict', 'Strict'), ('legacy', 'Legacy Compatibility'), ('experimental', 'Experimental')], default='standard', max_length=20),
        ),
    ]
