# Generated by Django 6.0.7 on 2026-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_validationissue_code_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='validation_scope',
            field=models.CharField(choices=[('complete', 'Complete LP'), ('html', 'HTML Only'), ('css', 'CSS Only'), ('javascript', 'JavaScript Only'), ('typescript', 'TypeScript Only')], default='complete', max_length=20),
        ),
    ]
