# Generated by Django 6.0.7 on 2026-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_validationreport_validation_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='source_block_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='source_context',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
