# Generated by Django 6.0.7 on 2026-08-04 08:42

from django.db import migrations, models


def backfill_language_from_file(apps, schema_editor):
    # Every issue created before this migration has `language == file`
    # (the two only diverge starting with Sprint CSS-A's embedded-CSS
    # adapters, which set both explicitly going forward) — a plain copy
    # is exact for all of them, not an approximation.
    ValidationIssue = apps.get_model('landingpages', 'ValidationIssue')
    ValidationIssue.objects.filter(language='').update(language=models.F('file'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0004_validationissue_source_block_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='language',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('cdn', 'CDN')], default='', max_length=20),
        ),
        migrations.RunPython(backfill_language_from_file, noop_reverse),
    ]
