# Generated by Django 6.0.7 on 2026-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0005_validationissue_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationissue',
            name='category',
            field=models.CharField(choices=[('syntax', 'Syntax'), ('accessibility', 'Accessibility'), ('seo', 'SEO'), ('security', 'Security'), ('performance', 'Performance'), ('responsive', 'Responsive'), ('structure', 'Structure'), ('property', 'Property'), ('value', 'Value'), ('compatibility', 'Compatibility')], max_length=20),
        ),
    ]
