# Generated by Django 6.0.7 on 2026-08-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0006_alter_validationissue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='source_asset_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
