# Generated by Django 6.0.7 on 2026-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0007_validationissue_source_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='generated_start_column',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='generated_start_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='css_source_type',
            field=models.CharField(choices=[('css', 'CSS'), ('scss', 'SCSS'), ('sass', 'Sass'), ('less', 'LESS')], default='css', max_length=10),
        ),
    ]
