# Generated by Django 6.0.7 on 2026-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0008_validationissue_generated_start_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageversion',
            name='ampscript_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='validationissue',
            name='file',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('ampscript', 'AMPscript'), ('cdn', 'CDN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='validationissue',
            name='language',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('ampscript', 'AMPscript'), ('cdn', 'CDN')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='validation_scope',
            field=models.CharField(choices=[('complete', 'Complete LP'), ('html', 'HTML Only'), ('css', 'CSS Only'), ('javascript', 'JavaScript Only'), ('typescript', 'TypeScript Only'), ('ampscript', 'AMPscript Only')], default='complete', max_length=20),
        ),
    ]
