# Generated by Django 6.0.7 on 2026-08-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0010_landingpagepreviewsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='analysis_coverage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='validationissue',
            name='category',
            field=models.CharField(choices=[('syntax', 'Syntax'), ('accessibility', 'Accessibility'), ('seo', 'SEO'), ('security', 'Security'), ('performance', 'Performance'), ('responsive', 'Responsive'), ('structure', 'Structure'), ('property', 'Property'), ('value', 'Value'), ('compatibility', 'Compatibility'), ('maintainability', 'Maintainability')], max_length=20),
        ),
    ]
