# Generated by Django 6.0.7 on 2026-08-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0012_repairknowledgerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoritativeKnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('rule_id', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(blank=True, default='', max_length=300)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(max_length=64)),
                ('retrieved_at', models.DateTimeField()),
                ('confidence', models.FloatField(default=0.3)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='candidate', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='landingpages.authoritativeknowledgerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'rule_id', 'status'], name='authoritative_kb_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'rule_id', 'source_url'), name='unique_authoritative_knowledge_source')],
            },
        ),
    ]
