# Generated by Django 6.0.7 on 2026-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0013_authoritativeknowledgerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='root_cause_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
