# Generated by Django 6.0.7 on 2026-08-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0014_validationissue_root_cause_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageversion',
            name='css_source_type',
            field=models.CharField(choices=[('css', 'CSS'), ('scss', 'SCSS'), ('sass', 'Sass'), ('less', 'LESS')], default='css', max_length=10),
        ),
    ]
