# Generated by Django 6.0.7 on 2026-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnrollmentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('encrypted_embedding', models.TextField()),
                ('embedding_version', models.PositiveSmallIntegerField(default=1)),
                ('model_name', models.CharField(max_length=100)),
                ('detector_backend', models.CharField(max_length=100)),
                ('distance_metric', models.CharField(max_length=50)),
                ('enrollment_frame_count', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
