# Generated by Django 6.0.7 on 2026-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceauth', '0002_faceenrollmentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecredential',
            name='engine_name',
            field=models.CharField(default='deepface', max_length=50),
        ),
        migrations.AddField(
            model_name='facecredential',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facecredential',
            name='threshold_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faceenrollmentproof',
            name='engine_name',
            field=models.CharField(default='deepface', max_length=50),
        ),
        migrations.AddField(
            model_name='faceenrollmentproof',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faceenrollmentproof',
            name='threshold_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
