# Generated by Django 6.0.7 on 2026-07-30 17:40

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID may only contain letters, numbers, and hyphens.', regex='^[A-Za-z0-9-]{1,50}$')])),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('manager_name', models.CharField(max_length=150)),
                ('date_of_joining', models.DateField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s()-]{7,20}$')])),
                ('date_of_birth', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=employees.models.profile_photo_upload_path)),
                ('registration_status', models.CharField(choices=[('PENDING_FACE_ENROLLMENT', 'Pending Face Enrollment'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING_FACE_ENROLLMENT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
