# Generated by Django 6.0.7 on 2026-08-19 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('generic', 'Generic'), ('sfmc', 'Salesforce Marketing Cloud'), ('marketo', 'Marketo'), ('hubspot', 'HubSpot'), ('pardot', 'Pardot / Account Engagement'), ('other', 'Other')], default='generic', max_length=20)),
                ('width', models.PositiveIntegerField(default=700, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(1200)])),
                ('start_type', models.CharField(choices=[('blank', 'Blank Email'), ('template', 'Template'), ('html', 'Existing HTML'), ('ai', 'AI Generate')], default='blank', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
