# Generated by Django 6.0.7 on 2026-08-19 20:11

import emailbuilder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildocument',
            name='content',
            field=models.JSONField(default=emailbuilder.models.default_content),
        ),
    ]
