# Generated by Django 6.0.7 on 2026-08-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0003_savedemailmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedemailmodule',
            name='columns',
            field=models.JSONField(default=list),
        ),
    ]
