# Generated by Django 6.0.7 on 2026-08-22 00:36

import django.db.models.deletion
import emailbuilder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0004_savedemailmodule_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('image', 'Images'), ('logo', 'Logos'), ('icon', 'Icons'), ('other', 'Others')], default='image', max_length=20)),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded file'), ('external', 'External URL')], max_length=20)),
                ('file', models.ImageField(blank=True, null=True, upload_to=emailbuilder.models.email_asset_upload_path)),
                ('external_url', models.URLField(blank=True, max_length=2000)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('content_type', models.CharField(blank=True, max_length=40)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
