# Generated by Django 6.0.7 on 2026-08-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0005_emailasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildocument',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='custom_css_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='email_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='favicon_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='reset_css_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
