# Generated by Django 6.0.7 on 2026-08-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0006_emaildocument_head_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedRepairSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=160)),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('source', models.CharField(choices=[('validation_center_single', 'Validation Center — single Fix'), ('validation_center_bulk', 'Validation Center — Fix All'), ('ai_engineer_repair', 'AI Engineer — repair proposal')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_repair_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'signature', 'created_at'], name='learnedrepairsignal_rank_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_id'), name='unique_learned_repair_signal_event')],
            },
        ),
    ]
