# Generated by Django 6.0.7 on 2026-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0011_emaildocument_outlook_vml_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedrepairsignal',
            name='source',
            field=models.CharField(choices=[('validation_center_single', 'Validation Center — single Fix'), ('validation_center_bulk', 'Validation Center — Fix All'), ('ai_engineer_repair', 'AI Engineer — repair proposal'), ('ai_engineer_reconstruction', 'AI Engineer — reconstruction repair')], max_length=30),
        ),
    ]
