# Generated by Django 6.0.7 on 2026-09-01 18:39

import django.db.models.deletion
import emailbuilder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0012_alter_learnedrepairsignal_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=emailbuilder.models.email_attachment_upload_path)),
                ('detected_type', models.CharField(choices=[('text', 'Text (.txt)'), ('csv', 'CSV (.csv)'), ('markdown', 'Markdown (.md)'), ('pdf', 'PDF (.pdf)'), ('docx', 'Word Document (.docx)'), ('xlsx', 'Excel Workbook (.xlsx)'), ('image', 'Image')], max_length=20)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=300)),
                ('extraction_meta', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emailbuilder.emaildocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'user', 'created_at'], name='emailattachment_doc_idx')],
            },
        ),
    ]
