# Generated by Django 6.0.7 on 2026-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbuilder', '0013_emailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedrepairsignal',
            name='source',
            field=models.CharField(choices=[('validation_center_single', 'Validation Center — single Fix'), ('validation_center_bulk', 'Validation Center — Fix All'), ('ai_engineer_repair', 'AI Engineer — repair proposal'), ('ai_engineer_reconstruction', 'AI Engineer — reconstruction repair'), ('ai_engineer_construction', 'AI Engineer — construction plan')], max_length=30),
        ),
    ]
